# Generated by Django 5.2.5 on 2025-08-06 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("normalized_title", models.CharField(db_index=True, max_length=255)),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "normalized_author",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "published_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("average_rating", models.FloatField(blank=True, null=True)),
                ("num_ratings", models.IntegerField(blank=True, null=True)),
                ("num_reviews", models.IntegerField(blank=True, null=True)),
                (
                    "cover_image_url",
                    models.URLField(blank=True, max_length=2000, null=True),
                ),
                (
                    "goodreads_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "goodreads_url",
                    models.URLField(blank=True, max_length=2000, null=True),
                ),
                (
                    "google_books_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("info_link", models.URLField(blank=True, max_length=2000, null=True)),
                ("isbn", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_website",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("review_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "reviewer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("review_text", models.TextField(blank=True, null=True)),
                ("review_date", models.DateField(blank=True, null=True)),
                (
                    "sentiment_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "sentiment_label",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="reviews.book",
                    ),
                ),
            ],
        ),
    ]
